spring:
  application:
    name: beijing-service-eureka
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: false
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    hostname: Server-beijing-ruanyan
  server:
    #关闭自我保护机制
    enable-self-preservation: false 
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    #地区
    region: beijing
    availability-zones:
      beijing: ruanyan,yizhuang
#      chengdu: chengdu-1,chengdu-2
    service-url:
      ruanyan: http://ruanyan.com:8761/eureka/
      yizhuang: http://yizhuang.com:8762/eureka/
#      chengdu-1: http://chengdu-1.com:8763/eureka/
#      chengdu-2: http://chengdu-2.com:8764/eureka/