spring:
  application:
    name: chengdu-2
server:
  port: 8764
eureka:
  instance:
    prefer-ip-address: false
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    hostname: Server-chengdu-2
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    remoteRegionUrlsWithName:
      beijing: http://ruanyan.com:8761/eureka/
    remoteRegionUrls: http://ruanyan.com:8761/eureka/
    remoteRegionAppWhitelist:
          beijing: http://ruanyan.com:8761/eureka/
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    #地区
    region: chengdu
    availability-zones:
#      beijing: ruanyan,yizhuang
      chengdu: chengdu-1,chengdu-2
    service-url:
#      ruanyan: http://ruanyan.com:8761/eureka/
#      yizhuang: http://yizhuang.com:8762/eureka/
      chengdu-1: http://chengdu-1.com:8763/eureka/
      chengdu-2: http://chengdu-2.com:8764/eureka/